### ISSUE TITLE
Discuss matching header on profiles page to that on index

### ISSUE THREAD

**Issue by disa-mhembere** [aschiffhauer/upe#1]
Looks ok but may be weird. I couldn't get the blue background to show up & quit after 5. 
Perhaps AS knows how

**Comment by CarloOlcese** [comment]
What do you mean? The blue banner looks the same across both the index.html and members.html

**Comment by disa-mhembere** [comment]
you should checkout the profiles branch and see an example profile & you'll see what I mean

**Comment by schiffy91** [comment]
I'll fix it and merge with master later tonight! Great work, Disa

**Comment by disa-mhembere** [comment]
Thanks. I actually merged to master because I edited the index & members
and I knew it would conflict if you added more members.
