### ISSUE TITLE
Sorted Members

### ISSUE THREAD

**Issue by schiffy91** [aschiffhauer/upe#5]
It'd be great to have our members sorted by year and then name.  Right now `members.py` spits out members in the order in which they appeared in `members.json`.  I don't want to add any javascript to our website, so perhaps we can delegate this responsibility to `members.py`.

**Comment by junr03** [comment]
Do you want them to be sorted by first name or last name?

**Comment by disa-mhembere** [comment]
I would support first name - it always looks better to me.

**Comment by schiffy91** [comment]
I agree with @dmhembe1.  I think we should sort by year (obviously) and then by first name.

**Comment by CarloOlcese** [comment]
Alphabetical order by height

**Comment by junr03** [comment]
I submitted a pull request. @CarloOlcese I didn't order by height but I think if we scrape some pictures based on name, year, and the fact that they went to Hopkins we could probably [predict height](http://www.umiacs.umd.edu/users/yaser/PID691698.pdf).
