### ISSUE TITLE
New registration workflow

### ISSUE THREAD

**Issue by schiffy91** [aschiffhauer/upe#6]
For this year's initiates, I built a very  [hacky node.js server](https://github.com/aschiffhauer/upe/tree/registration) that appends form responses into a JSON-like database.   This (essentially) allows copying-and-pasting the database into `members.json`.  Cool, I guess.

I'm of the opinion to keep our website as simple as possible.  Right now, it's server agnostic because the entire website is static.  In fact, we don't even use JavaScript! That's pretty sweet.

I don't think we should use a server/db for future registrations.  People will want to re-write the server and automate more and more of the process (increasing complexity).

Let's use this issue as place of discussion.  We can agree on something and include it in our repository's README.

My opinion: I think we should consider utilizing a doodle poll or some other technology.  

What are your thoughts?

**Comment by disa-mhembere** [comment]
I agree with the simplicity argument. KISS. I was under the impression Doodle was for scheduling meetings, but if they can do  this kind of survey -- great. If not, I've found survey monkey to do well for this type of thing.

**Comment by CarloOlcese** [comment]
I have no strong feelings towards either way, so here's my devil advocate for against what we are doing now...

JSON is kind of shiite for organizing stuff. Even looking at the current members.json page, It's hard to keep track of everything that's going on. I understand there is a script to generate this file, but that only makes it more convoluted (No comments FTW!). If you were to switch to some SQL-based/PHP implementation, you will be able to have easy-to-read tables as well as the ability to add columns easily, not to mention you could do more interesting queries (E.G. Filter members by year and interests).

Now of course this is a big jump all in the name of making a small honors society website look good, so I don't know if the effort is really justified. Just wanted to throw in my 2 cents.

**Comment by schiffy91** [comment]
KISS and don't over-engineer.

JSON is a lightweight data serialization format.  It's not as organized as SQL because it's not a relational database.  But we don't need a relational database.  We're not doing joins.  We're not doing unions.  We're not doing selects.

We have ~5-10 active members during the semester. We need no more than a lightweight, human readable (and thus diff-able) file.  Your options are XML or JSON -- feel free to choose your poison.  I went with JSON.

`members.json` is very organized, and it's incredibly easy to parse.  Take a look at our commit history and you'll see users have had no trouble editing their profiles and friends' profiles. This happened before we even had documentation.  We have a hierarchical decomposition of years, then members.  This is very intuitive.

It's straightforward enough that someone can open the file, CTRL-F their name, make changes, CTRL-S their changes, and commit.  That's a pretty nice workflow.  Is it as sexy as a SQL and PHP implementation? No.  But it's easier, more iterative, and requires less dependencies and knowhow.

The Python build script needs comments.  It's not clear (at all), and calling it hacky is giving it too much credit. But that's not the place for that discussion.  @CarloOlcese, feel free to open a new ticket and bash my code there.  I'll have time to add comments and clean it up sometime during this summer.

**Comment by CarloOlcese** [comment]
First off, we have 5-10 active members but we will have a ton of alumni...that's a lot of data to have in one huge JSON file.

Secondly, that workflow is not how it works because we have the JSON and the Python. If i edit the json and someone else runs the Python script it will delete those changes. This makes it not intuitive.

Thirdly, I'll take every opportunity to bash your code schiff <3

In conclusion, im in support of using json

**Comment by disa-mhembere** [comment]
Perhaps we can have an meeting post-exams to discuss the pros and cons and proceed with 1 method with all truly on-board?

**Comment by schiffy91** [comment]
@CarloOlcese

1) Yup. But all that data is at the bottom of the file.  I don't see why you'd scroll all the way to the class of 2000 unless you were taking a trip down memory lane.

2) False. `members.json` is the golden copy -- always.  `members.py` will always re-create `members.html` and each associated profile. This is a one-way relationship.  The only way your changes would be erased is if you edited `carlo_olcese.html` directly.  Perhaps we can rename the `members` folder to `temp`, so people really know not to edit their HTML page.  This information is already on the repository's README.

3) In the ticket, don't forget to ask why my code is not using `filter_and_transform` and `prune`.   The comments should at least mention the pigeon hole principle once, and last, but not least, I should re-write the entire script in oh-cuh-mull.

**Comment by schiffy91** [comment]
@dmhembe1, I will agree to meet only if @CarloOlcese brings his jungle juice to the meeting :trollface:

**Comment by CarloOlcese** [comment]
Im bringing it to the PL exam.

But again, I don't think there's any argument anymore. I agree we should continue what we're doing

**Comment by schiffy91** [comment]
@CarloOlcese, do you have an opinion on how we should handle registration for initiates? @dmhembe1 and I are of the opinion that SurveyMonkey is the easiest solution.  Would love to hear your non-devil's advocate opinion.

**Comment by disa-mhembere** [comment]
Yay for the jungle juice!

**Comment by CarloOlcese** [comment]
Does anyone know if you can easily download all of the data from survey
monkey? From my last experience with them (couple of months ago), it seemed
as though it would show you all of the data but not allow you to bulk
download it. This could be a bit tedious, let's look into it.

**Comment by disa-mhembere** [comment]
I wrote a very small and simple [Flask](http://flask.pocoo.org/) app to do this [here](https://github.com/upejhu/upe/tree/master/profile-submission). The submitted data needs concatenate then can be used as is to build the website. The form looks like [this](http://awesome.cs.jhu.edu/upe/)
